### PR TITLE
Updated and patched the cadmium playercore to the latest version

### PR DESCRIPTION
**Pull request by jangxx**
This fixed the endless loading on titles where switching to 5.1 audio did not suffice. I have only tested this on a few titles however, and I also have not verified that all the other features of the Extension work properly. This only fixes the endless loading bug.

### CODE REVIEW

**Comment by Fastigium** [comment]
Just tested it, and I can confirm that this PR allows me to watch the title I wanted to watch in 1080p where plain 1.19 exhibits the endless loading bug. Thanks so much :smile::tada:!

Not sure if it's ready to be merged into master, though. It lacks two updates to the cadmium playercore that the master branch has, namely:
```
<                 a.ctrlKey && a.altKey && a.shiftKey && a.keyCode == m.Zs.uOa &
& X.zS && u();
---
>                 a.ctrlKey && a.altKey && a.shiftKey && a.keyCode == m.Zs.uOa &
& u();
```
and:
```
<             this.Im = d ? "NFCDIE-04-" : c ? "NFCDOP-01-" : /Windows NT/.test(a) ? "NFCDCH-02-" : /Intel Mac OS X/.test(a) ? "NFCDCH-MC-" : b ? "NFCDCH-01-" : /Android.*Chrome\/[.0-9]* Mobile/.test(a) ? "NFCDCH-AP-" : /Android.*Chrome\/[.0-9]* /.test(a) ? "NFCDCH-AT-" : "NFCDCH-LX-";
---
>             this.Im = d ? "NFCDIE-04-" : c ? "NFCDOP-01-" : /Windows NT/.test(a) ? "NFCDIE-03-" : /Intel Mac OS X/.test(a) ? "NFCDIE-04-" : b ? "NFCDCH-01-" : /Android.*Chrome\/[.0-9]* Mobile/.test(a) ? "NFCDCH-AP-" : /Android.*Chrome\/[.0-9]* /.test(a) ? "NFCDCH-AT-" : "NFCDCH-LX-";
>             esnPrefix = this.Im;
```
I don't know what those two are supposed to do, but whatever it is, chances are that it's not working in this PR. At a guess, the first one re-enables Ctrl + Alt + Shift + S, which indeed does not work with this PR. I believe I read somewhere that that dialog has been completely stripped from recent cadmium playercores and that netflix-1080p uses an old core for that reason. The second one seems to change the result of some sort of platform detection, but I have no idea to what end.

**Comment by Fastigium** [comment]
Ah, I just remembered: I believe netflix-1080p uses the Ctrl + Alt + Shift + S dialog to lock the streaming quality to 1080p, so Netflix doesn't randomly decide to downgrade you to 720p at some point. If I'm correct, that's another part of extension functionality missing in this PR. Man, this is complicated

**Comment by jangxx** [comment]
Okay, I'm pretty sure I could easily add those things as well, if you're not faster than me 😉.

**Comment by Fastigium** [comment]
Go for it! I really should not be coding now, it'll ruin my sleep ^_^. I just successfully did the Ctrl + Alt + Shift + S patch (just remove `&& this.aX.pca` from `a.ctrlKey && a.altKey && a.shiftKey && a.keyCode == m.Bs.XXa && this.aX.pca && this.toggle();`) and now the forced bitrate seems to work again! I'm signing off for today, thanks again for your work :smiley:!

**Comment by jangxx** [comment]
There you go, I added both of the patches back in. I'm still not sure what 

```javascript
this.bx = f ? "NFCDTS-01-" : c ? "NFCDOP-01-" : /Windows NT/.test(a) ? "NFCDIE-03-" : /Intel Mac OS X/.test(a) ? "NFCDIE-04-" : b ? "NFCDCH-01-" : /Android.*Chrome\/[.0-9]* Mobile/.test(a) ? "NFCDCH-AP-" : /Android.*Chrome\/[.0-9]* /.test(a) ? "NFCDCH-AT-" : "NFCDCH-LX-";
```

is supposed to do, though. It has to have something to do with the user-agent, but I have no idea what the meaning of these `NFCDxx-xx-` codes is.

**Comment by OothecaPickle** [comment]
this breaks audio option descriptions, but it does fix the endless loading thing.

old

new

**Comment by jangxx** [comment]
Does the `c9a` thing change anything for you though? I tried it with `channelsFormat` and `c9a` and even something like `+ "blabla"`, but the text in the UI never changes.

**Comment by Yrp** [comment]
it works for me

**Comment by coxackie** [comment]
hey, guys, since this PR does not seem probable to be merged, anyone wants to provide a new crx file in one of the forked repos for everyone to be able to use?

**Comment by jangxx** [comment]
@coxackie Here you go I guess: https://github.com/jangxx/netflix-1080p/releases/tag/v1.20

My repo is only temporary though, and I will delete it, as soon as this one has an official fixed version.

**Comment by coxackie** [comment]
@jangxx many thanks. Let's hope that this repo will get updated, but @truedread has not appeared for quite some time now...

**Comment by coxackie** [comment]
Can also confirm that the audio option descriptions still miss the quality.

**Comment by jangxx** [comment]
Okay, I think the missing channel information should be fixed now.

**Comment by EmyShoka** [comment]
Working perfectly, thank you so much !!

**Comment by coxackie** [comment]
can also confirm! great job!

**Comment by lkmvip** [comment]
nice

**Comment by Cyborgscode** [comment]
how can we add the v1.20 build to firefox? As Temp-Addon it did not work.

**Comment by jangxx** [comment]
I don't use Firefox and know nothing about it's extension system, but the changes from 1.19 to 1.20 really don't introduce any Chrome specific features, so I don't know why it doesn't work. Are you getting a specific error message? Also what is a "Temp-Addon"? Does the Firefox version have some additional Firefox specific code to make it work? Maybe the authors of the Firefox version should take a look.

**Comment by jangxx** [comment]
I took a quick look at the code, and apparently the Firefox version's `background.js` is very different, because it actually loads the patched js file instead of just redirecting the request. I guess you could try to copy the patched `cadmium-playercore-6.0023.327.011-1080p.js` into the Firefox addon and replace  it's `cadmium-playercore-1080p.js`. Maybe that's all that's needed to get the addon working again.

**Comment by Cyborgscode** [comment]
a temp-addon if for debug purposes. You get into a special addon context with more control and some tools. It's unkown if that runs in a different mode, than a normal addon. I will try your suggestion and keep reporting.

**Comment by lkmvip** [comment]
"heaac-2hq-dash",

add 128 bit audio ，for channels 2.0

**Comment by shtu-cham** [comment]
Hi, jangxx. Thank you for your work! I am confused since the extension you fixed did work, but today when I reuse it I notice the bitrate is finally limited as 720P and even lower. I confirm that my network speed is OK, and this problem occured when I used the v1.19. Just don't know why it can't unlock all the videos under 1080P. Wonder if this problem happens to you guys, thank you.

**Comment by jangxx** [comment]
@shtu-cham Can you link to a title where this problem happens? Maybe the title is simply not available in a higher resolution than 720p.

**Comment by Cyborgscode** [comment]
BTW: if you use truedreads plugin in Chrome, you can use CTRL+ALT+SHIFT+S to select the service node, the bitrate aso. This would be nice to have on ff too (and would solve his problem ) :)

**Comment by shtu-cham** [comment]
> @shtu-cham Can you link to a title where this problem happens? Maybe the title is simply not available in a higher resolution than 720p.

Thank you for replying! **Prison break**, season 5, I am watching it under 720P **at HK** right now, it was offered at 2017. Besides, I am also watching **IRON MAN 2** under 960✖540, I can change the service node but none of them can offer higher resolution. Don't know if both of them can only be watched under 720P, cause Netflix didn't offer this kind of information like the highest bitrate of these videos. Or the resolution of these two maybe limited by the region.

Again, thank you for your time!

**Comment by shtu-cham** [comment]
> BTW: if you use truedreads plugin in Chrome, you can use CTRL+ALT+SHIFT+S to select the service node, the bitrate aso. This would be nice to have on ff too (and would solve his problem ) :)

Thank you for helping me! Yes, I did change the service node, and I press the override buttion, but the bitrate remained the same, don't know what was wrong.

**Comment by Cyborgscode** [comment]
Iron Man and most of Marvel movies are not available in FULLHD @ Netflix. They are just DVD copies.

**Comment by shtu-cham** [comment]
> Iron Man and most of Marvel movies are not available in FULLHD @ Netflix. They are just DVD copies.

Though Iron Man can be displayed under high resolution in Microsoft Edge which is not the chromium one. That confuses me.

**Comment by starm7md** [comment]
@jangxx  have this error D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error D7354 ,iam on windows 10 the versions of the browser aren't the problem because i've tried old and new versions and all of them have the same problem , please begging for help 
n shoot
n shoot 2

**Comment by jangxx** [comment]
@starm7md Why are you using this extension with Edge in the first place? I'm pretty sure that Edge is among the browsers which even support up to UHD resolution (https://help.netflix.com/en/node/13444), so why would you need an extension to unlock that for you? The primary target of this extension is users who desperately want to use Chrome, or those who are on unsupported operating systems (like Linux) and have no other option. If you are on a supported OS you might as well use the official Netflix app (Windows) or the officially supported Edge browser, for which you don't need an extension to get 1080p or UHD resolution.

**Comment by starm7md** [comment]
@jangxx   To force the browser to set high quality uhd  because as you know watching high quality Netflix on browser it depends totally on the internet speed and you need to have decent internet speed and stable without this the quality will keep changing like what's happening to me , the quality changes every 5 minutes from high to low quality and opposite same also on Netflix app windows , so the only way i can watch 1080p is on Microsoft edge with this extension , if there anyway i can fix this or you now any type of solution its very appreciate it

**Comment by shtu-cham** [comment]
> @jangxx To force the browser to set high quality uhd because as you know watching high quality Netflix on browser it depends totally on the internet speed and you need to have decent internet speed and stable without this the quality will keep changing like what's happening to me , the quality changes every 5 minutes from high to low quality and opposite same also on Netflix app windows , so the only way i can watch 1080p is on Microsoft edge with this extension , if there anyway i can fix this or you now any type of solution its very appreciate it

So have you tried turning off hardware acceleration in Chromium Edge? Settings-System, please. You should check the error code yourself. It isn't the problem of extension. Again, thank jangxx for his work.

**Comment by starm7md** [comment]
yes i have tried but it didnt fix it , it shows the same error D7354 this error  is on my all windows devices  , anyway thanks to @jangxx and thanks to @shtu-cham for respond at least

**Comment by shtu-cham** [comment]
> yes i have tried but it didnt fix it , it shows the same error D7354 this error is on my all windows devices , anyway thanks to @jangxx and thanks to @shtu-cham for respond at least

Then I recommend you open the DRM feature in edge://flags, give it another try. Good luck.

**Comment by lkmvip** [comment]
I said, Chromium Edge can only use cadmium-playercore-*. ****. ***. 031.js, download this file from Netflix, put it in the plugin directory, modify manifest.json and background.js


Chromium Edge V80 and later versions can only watch 720P and lower，add profile “playready-h264hpl40-dash“ to watch 1080P, but it is essentially the same as Chrome, E.g IRON MAN 2 is 540P，only the version before V79 is worth having，It has complete DRM。

**Comment by psvita123** [comment]
> I said, Chromium Edge can only use cadmium-playercore-*. ****. ***. 031.js, download this file from Netflix, put it in the plugin directory, modify manifest.json and background.js
> 
> Chromium Edge V80 and later versions can only watch 720P and lower，add profile “playready-h264hpl40-dash“ to watch 1080P, but it is essentially the same as Chrome, E.g IRON MAN 2 is 540P，only the version before V79 is worth having，It has complete DRM。
> 
> V79 and previous versions can use edge: // flags, turn on HEVC switch, minimum 1080P, maximum 4K

is there any way to download V79 of edge. I tried googling but nothing came up.

**Comment by starm7md** [comment]
@psvita123 yes , you can find it in this like , but it won't change much the only way u can use the extension on all versions is by turning of the hardware acceleration otherwise it won't work and it will show an error  Or as far as I know , and if there anyone knows how i can use it with hardware acceleration please let us know 

https://www.catalog.update.microsoft.com/Search.aspx?q=Edge


and also after you download old version you have to stop the version from updating its self and you can find u can find details on this link and do both methods to make sure it has stopped 

https://winaero.com/blog/prevent-microsoft-edge-chromium-from-installing-via-windows-update/

**Comment by starm7md** [comment]
and also make sure that u are using that last version of the extension which has updated recently 
https://github.com/jangxx/netflix-1080p/releases/tag/v1.20

all credits for this guy @jangxx

**Comment by lkmvip** [comment]
@psvita123 

v79.0.309.71 Stable
http://dl.delivery.mp.microsoft.com/filestreamingservice/files/f201d5b2-6909-4d49-9c8f-c93edf559b07/MicrosoftEdgeEnterpriseX64.msi

**Comment by Loukky** [comment]
@jangxx some videos still broken 
break : https://www.netflix.com/watch/70143635?trackId=14277281&tctx=0%2C0%2C4de20caf-e42e-48e2-a526-98112cb6546f-203707108%2C%2C%2C
error code:M7336

**Comment by lkmvip** [comment]
@jangxx some videos still broken


open cadmium-playercore-6.0023.327.011-1080p.js

replace "NFCDIE-03-" to "NFCDCH-02-"

**Comment by Loukky** [comment]
@lkmvip its working for me,thank you very much!

**Comment by jangxx** [comment]
@lkmvip So is this an issue with the Chrome extension or with the Edge extension? In other words; do I have to add this change to this pull request as well or is it unrelated to the Chrome version of the extension?

**Comment by lkmvip** [comment]
@jangxx

I think only need to add 1080P profiles, no need to modify NFCDXX

I don’t know why truedread modified it, but I think it will cause accidents, and in fact it is

because Netflix defines Chrome as NFCDCH

**Comment by jangxx** [comment]
I'm guessing that the last two letters specify the browser (or browser engine), so _NFCD_**CH** is Chrome, _NFCD_**IE** is Internet Explorer (i.e. Edge) and so on. Since Edge was a supported browser in the past, I assume that truedread wanted to fool the server into thinking that it was actually an Edge browser requesting the video and not Chrome. Since Edge switched to using Chromium, Netflix probably decided to just classify it as another Chrome browser, which is why it is now also assigned the NFCDCH prefix.

Anyway, I think I agree with you, that the "pretending to be Edge" thing is no longer necessary, so it makes sense to just change those identifiers back to their original form.

**Comment by SoapTastesBad** [comment]
how do i activate 5.1?

**Comment by tmac21** [comment]
> this breaks audio option descriptions, but it does fix the endless loading thing.
> 
> old
> 
> new

How can I take it back?

**Comment by Invictaz** [comment]
@jangxx @truedread @lkmvip seems that it fails again and quite some movies are back to 540p (Ted 2 for example).
I use the 1.20.1 from @jangxx but it doesn't work anymore?

**Comment by jangxx** [comment]
Could that simply be a problem of unavailability, a problem with your internet, or something else unrelated to this extension? The only thing I fixed was the playback not starting _at all_. If the movie plays, I'm not sure there's a problem with the extension. Have you tried to manually select a higher resolution and bitrate in the Ctrl+Shift+Alt+S menu?

**Comment by Invictaz** [comment]
@jangxx with CTRL+ALT+Shift+S there is no higher bitrate. However: when I watch the same serie/movie on my phone with Chromecast I swear that it is much higher quality.

**Comment by jangxx** [comment]
I tried to reproduce your issue and I can indeed confirm, that (at least) the movie "Ted" is only available in 540p with a 300 kbps something bitrate, which is pretty atrocious. I'm really not sure if we could fix this in the extension however, since Netflix doesn't seem to provide any higher bitrate versions. But tbh I'm far from an expert on the Netflix player and their server infrastructure - All I did was port a patch from a previous cadmium player to a newer version and that's it. I don't have the time or energy to investigate if there might be some other way to convince the Netflix servers of giving us a higher bitrate, but maybe someone else does.

**Comment by Invictaz** [comment]
@jangxx That's why I tagged the other guys 
I tried also @lkmvip Edge Chromium but it refuses to load giving some Netflix error.

**Comment by lkmvip** [comment]
Chrome and versions prior to win8 do not have DRM

If you need to always use the highest quality streaming, you must use the version after win8, and the edge or NetflixApp

I recommend using Windows 10

**Comment by Invictaz** [comment]
@lkmvip Windows 7 + Chrome has Widevine and it did work in 1080P until a month ago.

**Comment by lkmvip** [comment]
@Invictaz If you plan to use my modified extension, please use win10

@jangxx I think it can only be faked as an edge list

**Comment by Invictaz** [comment]
The only thing I can think of that should be different is HEVC on Windows 10. I don't need 4K so

**Comment by lkmvip** [comment]
Why don't you understand?

its about drm ,in pc , for Netflix, widevine is Low-level DRM, playready is High-level DRM

in low level,  you can only watch 540P SONY movies and some episodes, This is the Netflix DRM limit

Everything is for DRM, in order to watch high-quality Netflix on PC, you can only upgrade to WIN10 , only, no more

**Comment by Invictaz** [comment]
@lkmvip This was not true, as I used 1080P on Win7 until a couple of weeks ago. Maybe Netflix changed something. 
And Playready is phased out with OldEdge. EdgeChromium does not have Playready as far as I know.

**Comment by lkmvip** [comment]
Simply put, your idea cannot be reached, and there will be more and more 540P in the future

**Comment by Invictaz** [comment]
What exact file is missing on Windows 7? Libwidevinecdm.dll is there

**Comment by lkmvip** [comment]
no，for Netflix, playready drm only work on win10 maybe and win8

**Comment by jangxx** [comment]
@lkmvip Are you sure this is purely a problem with the DRM though? I tried it myself with Chrome on Windows 10 and I was only able to play "Ted" in 540p.

**Comment by lkmvip** [comment]
yes，its drm


Netflix believes Chrome is not safe, so you must use win10 and edge or NetflixApp or edge (Chromium core), because this time Netflix will use the playready drm, it thinks safe

**Comment by jangxx** [comment]
I think you might be right. I read [this article](https://medium.com/pallycon/why-cant-i-watch-netflix-in-ultra-hd-on-my-chrome-browser-525933dad5bb), which agrees with most of what you have said. It seems like Netflix is fine with Widevine for 1080p viewing of it's own content and some other providers are fine with Widevine as well, but certain studios seem to restrict even 720p playback to PlayReady DRM, which is only available on Edge.

I guess this means we are SOL and this extension is only useful for Netflix's own content and that of some other studios but it doesn't allow 1080p playback of _every_ piece of media.

**Comment by lkmvip** [comment]
So I now use edge(Chromium core) , Because my hardware supports 4K

if you use win10 and edge or NetflixApp or edge (Chromium core), if you don't have 4K hardware, you can watch 1080P, without expansion

**Comment by Invictaz** [comment]
But why does the Android app support 1080p while Chrome on Android does not?

**Comment by Luckz** [comment]
> @Loukky
> 
> open cadmium-playercore-6.0023.327.011-1080p.js
> 
> replace "NFCDIE-03-" to "NFCDCH-02-"
> 
> In fact, "NFCDCH-02-" is the original value provided by Netflix，work on Chrome and Firefox，"NFCDIE-03" is for edge

But wouldn't only NFCDIE-03- and something like NFUWA-001- even be allowed full HD streams?

Neither of them can be screencapped with printscreen or Win-shift-S by the way.

**Comment by lkmvip** [comment]
NFCDIE for ie,its Need playready drm, if not, then use WidevineCdm Or throw an error message

NFUWA only work on win8/win10 NetflixApp, It uses a special playback core， its use playready drm

In playready drm protection, it is impossible to record and take screenshots

**Comment by truedread** [comment]
Closing as this is a year old.

**Pull request closed without merging**
