### PR TITLE
Update jsSHA url because upstream changed to TypeScript

### PR DESCRIPTION
**Pull request by jlsalvador**

### CODE REVIEW

**Comment by jangxx** [comment]
This does not work for me; I still get the same `cadmium-playercore` errors and an endlessly loading video.

**Comment by starm7md** [comment]
9i have the same error D7354 on Microsoft edge (Chromium build) Version 81.0.416.72 as soon as i play some video it shows error D7354 ,iam on windows 10 the versions aren't the problem because i've tried old and new versions and all of them have the same problem , please begging for help 

n shoot
n shoot 2

**Comment by jlsalvador** [comment]
Please @starm7md stop. This is NOT a forum support. You're posting your offtopic across all pull requests. Open an ISSUE and wait for the community support. If you can't wait, consider to pay someone to fix it.

**Comment by starm7md** [comment]
Ok

**Comment by truedread** [comment]
Closing as jsSHA is no longer used.

**Pull request closed without merging**
